### ISSUE TITLE
Filter the list of jargon to remove any non-medical terms

### ISSUE THREAD

**Issue by jonjiang1** [higgood/med-jargon-explain-inator#10]
Note: Can be done either manually or through prompt-tuning

AC:
- [x] **Document the data sources (for definitions) and steps for processing it in one of the MD files.**
- [x] Alter committed list to remove non-medical jargon
- [x] List updated in the repo
- [x] Acronyms should be preserved with their full expansion in a separate file

Potentially useful resource:
giant list of medical abbreviations: https://github.com/imantsm/medical_abbreviations

**Comment by wammar** [comment]
Melody's update: Now using a variety of medical references to check each term in the list of ~1700 terms, including abbreviations. About 150 lines were excluded. 

The source of this list is the April 24, 2024 version of this file: https://medlineplus.gov/xml/mplus_topics_2024-05-03.xml

**Comment by wammar** [comment]
Emma is almost done with her part of this. The remaining piece is to add the list of categories we're filtering on.

Melody is actively working on this.
