### ISSUE TITLE
Simplify a definition

### ISSUE THREAD

**Issue by jonjiang1** [higgood/med-jargon-explain-inator#12]
AC:
- [ ] Given a definition and its readability score, define a threshold of "too difficult"
- [ ] If the definition exceeds the threshold, simplify the definition (can be done via prompt tuning or some other LLM method)

**Comment by wammar** [comment]
- BERT model was trained (IN 4 DAYS!!!) 
- Test code is buggy, Ben is planning to use a more recent and domain-specific evaluation setup to gauge how good this model is. https://arxiv.org/pdf/2302.05574

**Comment by wammar** [comment]
We switched to pretrained models, no fine tuning. Ben evaluated three LLMs  (BART, T5, Pegasus) using the same dataset, against METEOR (F1-based), Rouge1, and Rouge2 (RougeX uses n-gram counts). Quantitative results and anecdotal evidence suggest that T5 gives the best results.

Automated evaluation remains a challenge. 

Ben used T5 base, bigger than the small and not as big as the L and XL.

**Comment by wammar** [comment]
If we decide to improve this further, using a larger model (T5 XL or something entirely different such as llama) might be the most effective way to do so.

**Comment by wammar** [comment]
Pending review. @jonjiang1 kindly agreed to do it.
