### ISSUE TITLE
Evaluate readability of definition

### ISSUE THREAD

**Issue by jonjiang1** [higgood/med-jargon-explain-inator#13]
AC:
- [x] Given a definition (string of text) provide some readability metric for the definition
- [x] quantify the readability in two metrics: general definition, medical jargon terms
- [x] document with readme file

**Comment by zepam** [comment]
I am using a reading ease number for this. 0 is hardest and 100 is easiest.

**Comment by zepam** [comment]
Done. Need to submit pull request to get it checked.

**Comment by wammar** [comment]
Update: We discussed a number of ways this can be used to further the goal of this project:
1. Assessing how effective the simplification component is.
2. Determining which definition to use, and whether it needs to be simplified.

Update: @zepam will consider removing the term itself from the computation and decide if the scores are more useful then.

**Comment by wammar** [comment]
Remaining piece is to document in the README file.

**Comment by wammar** [comment]
This is done.

**Comment by wammar** [comment]
The Flesch Kincaid Grade Level (FKGL) measure is a popular way to evaluate the reading difficulty of text. The American Medical Association suggests a goal of sixth grade as the target reading level.
