### ISSUE TITLE
Define and implement an API endpoint for retrieving a list of definitions given a phrase/term.

### ISSUE THREAD

**Issue by wammar** [higgood/med-jargon-explain-inator#20]
Acceptance Criteria:
- Create a REST endpoint using FastAPI that takes a phrase/term and returns a list of definitions
- (Optional) Unit tests

**Comment by jonjiang1** [comment]
GET REST endpoint
Input: single String containing the term we want the definition for
Output: 
- If the term is not in the dictionary, return None
- If the term is in the dictionary but has no definitions, return an empty list
- Else return a list containing all the definitions for a given word
