### ISSUE TITLE
Work with HS Library to continue search for databases

### ISSUE THREAD

**Issue by zepam** [higgood/med-jargon-explain-inator#3]
Contact librarians of the Health Sciences library to ask:

- do we already have access/licenses for databases
> - Emma is working on UMLS license
> - Melody is working on MedJ
- are there particular dbs that would work well for us?

**Comment by jonjiang1** [comment]
5/3 Status Update:
- Got a textbook recommendation from HLS librarian
- Reached out for more resources that would fit our needs
- Asked about USMLJ licensing

**Comment by zepam** [comment]
5/6 status update:
* didn't get any additional helpful info from the librarian.
* suggest we continue on with the work Emma and Melody are doing
