### ISSUE TITLE
Sending out the UXR questionnaire(s) for users to fill out.

### ISSUE THREAD

**Issue by wammar** [higgood/med-jargon-explain-inator#6]
There are two questionnairs that we developed so far:
1. [Foundational UXR survey](https://docs.google.com/forms/d/e/1FAIpQLSc_1VXATYr2OuiFZLM9WaCusehf-3EP3dg577P7GR7Ku79niA/viewform).
2. [UX-focused questionnaire](https://docs.google.com/document/d/1xGyfEZjuy2FDWpWbMpJ44ABZNkixEM5caDZNwvMcTCY/edit#heading=h.amyw4cokgdpg).

We will only be sending out the first one before the end of the quarter, because the IRB is approved.

Steps:
- [x] Identify participant eligibility criteria.
- [x] Identify channels for broadcasting the survey link.
- [x] Send the google form for first survey.
- [x] @ecm68 and @hopems7 to draft comms/marketing around the survey
- [x] Rally other team members to send it out as well.
- [ ] Survey to be open for 2 weeks (May 17th) to allow for collection of responses. @ecm68 to close form on 17th.

**Comment by wammar** [comment]
Emma: Team explored channels for sending this out. 
Melody: Filled out the questionnaire to test out the process.

**Comment by wammar** [comment]
Melody clarified that the IRB is only good for the first survey, not the second. We can modify the IRB and review it if needed.

**Comment by jonjiang1** [comment]
5/3 Update
- Melody added question
- Emma drafted list of subreddits to post and drafted post

Action Items:
- Emma to post form link to Discord
- Everyone to share to their social spaces, post in Discord about where the survey's been so we can keep track.

**Comment by wammar** [comment]
The bulk of the work is done but keeping it open to remind ourselves to publicize it until it closes on May 17th.

As of now: 46 responses! Mostly healthcare workers.

**Comment by wammar** [comment]
The survey is closed, with 49 responses. Age range 18-75, most between 18-44. Neurodivergent population is about 50%.

**Comment by wammar** [comment]
@ecm68 Kindly share the data with me at wammar@holistic-intelligence.net OR waleed.ammar@gmail.com
