### ISSUE TITLE
Compile (and commit to repo) list of jargon

### ISSUE THREAD

**Issue by jonjiang1** [higgood/med-jargon-explain-inator#9]
As a ML trainer, I want a list of jargon I can train a model on so that I can detect jargon in context.

Acceptance Criteria:
- [x] Lists of jargon (can be medical or non-medical) identified and gathered
- [x] Lists merged into one larger list
- [x] List of definitions committed to repo, JSON like structure (see below)
- [x] Task owner to decide format of the list

{
  term: term1
  def1: long definition with stuff
  def2: even longer definition
}

**Comment by wammar** [comment]
Update: @ecm68 is working on integrating UMLS data and merging it with the other sources.

**Comment by wammar** [comment]
Next step is to convert the additional non-UMLS terms into the same format Emma is using for the UMLS terms, and merging them, then committing to git, and pushing to origin. 

Bridger recommends also adding one script with a bit of documentation on how to use it.

No additional dependencies needed.

@hopems7
